version: '3.1'

services:
  web:
    build: .
    ports:
      - "10000:80" # On mappe le port 10000 vers 80
    environment:
      - DB_HOST=mysql-backend-09vk.onrender.com
      - DB_PORT=3306
      - DB_DATABASE=my_database
      - DB_USERNAME=mysql
      - DB_PASSWORD=RenderMysqlPassword
      - APP_PORT=10000 # Ajout pour Laravel
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RenderMysqlPassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: mysql
      MYSQL_PASSWORD: RenderMysqlPassword

volumes:
  db_data:
