# 3. render.yaml
services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: storage
      mountPath: /var/www/storage
    envVars:
      - key: PORT
        value: 80
      - key: DB_HOST
        value: mysql-backend-09vk.onrender.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: my_database
      - key: DB_USERNAME
        value: mysql
      - key: DB_PASSWORD
        value: RenderMysqlPassword